'use client';

import { useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { motion } from 'framer-motion';
import { createClient } from '@/lib/supabase/client';
import { Navbar } from '@/components/navigation/Navbar';
import { Card, CardContent, CardHeader } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Contract } from '@/types/database';
import {
    FileText,
    Download,
    ArrowLeft,
    Calendar,
    Users,
    Sparkles,
    Copy,
    Check,
    Shield,
    Clock,
} from 'lucide-react';
import { format } from 'date-fns';

export default function ContractDetailPage() {
    const params = useParams();
    const router = useRouter();
    const contractId = params.id as string;

    const [contract, setContract] = useState<Contract | null>(null);
    const [loading, setLoading] = useState(true);
    const [downloading, setDownloading] = useState(false);
    const [copied, setCopied] = useState(false);

    useEffect(() => {
        const fetchContract = async () => {
            const supabase = createClient();

            const { data, error } = await supabase
                .from('contracts')
                .select('*')
                .eq('id', contractId)
                .single();

            if (error) {
                console.error('Error fetching contract:', error);
                router.push('/contracts');
                return;
            }

            setContract(data);
            setLoading(false);
        };

        if (contractId) {
            fetchContract();
        }
    }, [contractId, router]);

    const handleDownload = async () => {
        if (!contract) return;
        setDownloading(true);

        // Get the LLM-generated contract text
        const generatedText = contract.final_content?.generatedText || '';

        // Create text content with header
        const content = `
================================================================================
                    ${contract.title.toUpperCase()}
================================================================================
Generated: ${format(new Date(contract.created_at), 'MMMM d, yyyy')}
Template: ${contract.final_content?.templateName || 'Contract'}
================================================================================

${generatedText}

================================================================================
                    END OF CONTRACT DOCUMENT
================================================================================
Generated by PseudoLawyer - AI-Assisted Contract Negotiation Platform
`;

        // Create blob and download
        const blob = new Blob([content], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${contract.title.replace(/\s+/g, '_')}_Contract.txt`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);

        setDownloading(false);
    };

    const handleCopy = async () => {
        if (!contract?.final_content?.generatedText) return;

        await navigator.clipboard.writeText(contract.final_content.generatedText);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    if (loading) {
        return (
            <div className="min-h-screen flex items-center justify-center">
                <div className="text-center">
                    <div className="w-12 h-12 border-2 border-magenta border-t-transparent rounded-full animate-spin mx-auto mb-4" />
                    <p className="text-white/60">Loading contract...</p>
                </div>
            </div>
        );
    }

    if (!contract) {
        return null;
    }

    const parties = contract.final_content?.parties || [];
    const generatedText = contract.final_content?.generatedText || '';

    return (
        <div className="min-h-screen">
            <Navbar />

            <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
                {/* Header */}
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="mb-8"
                >
                    <Button variant="ghost" size="sm" onClick={() => router.push('/contracts')} className="mb-6">
                        <ArrowLeft className="w-4 h-4" />
                        Back to Contracts
                    </Button>

                    <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-6">
                        <div className="flex items-start gap-4">
                            <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-magenta to-cyan flex items-center justify-center shadow-glow-magenta shrink-0">
                                <FileText className="w-8 h-8 text-white" />
                            </div>
                            <div>
                                <h1 className="text-2xl sm:text-3xl font-bold font-display text-white mb-2">
                                    {contract.title}
                                </h1>
                                <div className="flex flex-wrap items-center gap-3 text-sm text-white/50">
                                    <div className="flex items-center gap-1.5">
                                        <Calendar className="w-4 h-4" />
                                        {format(new Date(contract.created_at), 'MMMM d, yyyy')}
                                    </div>
                                    <span className="w-1 h-1 rounded-full bg-white/30" />
                                    <div className="flex items-center gap-1.5">
                                        <Sparkles className="w-4 h-4 text-cyan" />
                                        AI Generated
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div className="flex gap-3">
                            <Button variant="secondary" onClick={handleCopy}>
                                {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                                {copied ? 'Copied!' : 'Copy'}
                            </Button>
                            <Button onClick={handleDownload} loading={downloading}>
                                <Download className="w-4 h-4" />
                                Download
                            </Button>
                        </div>
                    </div>
                </motion.div>

                {/* Contract Content */}
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.1 }}
                    className="space-y-6"
                >
                    {/* Template Info */}
                    <Card variant="gradient">
                        <CardContent className="p-6">
                            <div className="flex items-center justify-between">
                                <div className="flex items-center gap-4">
                                    <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-cyan to-magenta flex items-center justify-center">
                                        <FileText className="w-6 h-6 text-white" />
                                    </div>
                                    <div>
                                        <h2 className="text-lg font-semibold font-display text-white">
                                            {contract.final_content?.templateName || 'Contract'}
                                        </h2>
                                        <p className="text-sm text-white/50">AI-Generated Legal Contract</p>
                                    </div>
                                </div>
                                <div className="flex items-center gap-2 px-4 py-2 rounded-full bg-success/10 border border-success/20">
                                    <div className="w-2 h-2 rounded-full bg-success animate-pulse" />
                                    <span className="text-sm text-success font-medium">Finalized</span>
                                </div>
                            </div>
                        </CardContent>
                    </Card>

                    {/* Parties */}
                    {parties.length > 0 && (
                        <Card variant="elevated">
                            <CardHeader>
                                <div className="flex items-center gap-3 text-white">
                                    <div className="w-10 h-10 rounded-xl bg-cyan/10 flex items-center justify-center">
                                        <Users className="w-5 h-5 text-cyan" />
                                    </div>
                                    <div>
                                        <h2 className="text-lg font-semibold font-display">Contract Parties</h2>
                                        <p className="text-sm text-white/50">Participants in this agreement</p>
                                    </div>
                                </div>
                            </CardHeader>
                            <CardContent className="space-y-3">
                                {parties.map((party: any, index: number) => (
                                    <div
                                        key={index}
                                        className="flex items-center justify-between p-4 rounded-xl bg-white/[0.03] border border-white/[0.06]"
                                    >
                                        <div className="flex items-center gap-3">
                                            <div className="w-10 h-10 rounded-full bg-white/10 flex items-center justify-center">
                                                <span className="text-sm font-semibold text-white">
                                                    {party.name?.charAt(0)?.toUpperCase() || '?'}
                                                </span>
                                            </div>
                                            <div>
                                                <p className="font-medium text-white">{party.name}</p>
                                                <p className="text-sm text-white/50">{party.email}</p>
                                            </div>
                                        </div>
                                        <span className="px-3 py-1.5 rounded-full text-xs font-medium bg-cyan/10 text-cyan border border-cyan/20">
                                            {party.role}
                                        </span>
                                    </div>
                                ))}
                            </CardContent>
                        </Card>
                    )}

                    {/* Generated Contract Text */}
                    <Card variant="elevated">
                        <CardHeader>
                            <div className="flex items-center justify-between">
                                <div className="flex items-center gap-3 text-white">
                                    <div className="w-10 h-10 rounded-xl bg-magenta/10 flex items-center justify-center">
                                        <FileText className="w-5 h-5 text-magenta" />
                                    </div>
                                    <div>
                                        <h2 className="text-lg font-semibold font-display">Contract Document</h2>
                                        <p className="text-sm text-white/50">Full legal text</p>
                                    </div>
                                </div>
                                <Button variant="ghost" size="sm" onClick={handleCopy}>
                                    {copied ? <Check className="w-4 h-4 text-success" /> : <Copy className="w-4 h-4" />}
                                </Button>
                            </div>
                        </CardHeader>
                        <CardContent>
                            <div className="relative">
                                {/* Document styling */}
                                <div className="absolute -inset-px rounded-xl bg-gradient-to-br from-magenta/20 via-transparent to-cyan/20 opacity-50" />
                                <div className="relative p-8 rounded-xl bg-white/[0.02] border border-white/[0.08] max-h-[600px] overflow-y-auto">
                                    <pre className="contract-text text-sm whitespace-pre-wrap font-body leading-[1.8]">
                                        {generatedText || 'No contract content available.'}
                                    </pre>
                                </div>
                            </div>
                        </CardContent>
                    </Card>

                    {/* AI Notice */}
                    <Card className="border-cyan/20 bg-gradient-to-r from-cyan/5 to-magenta/5">
                        <CardContent className="p-6">
                            <div className="flex items-start gap-4">
                                <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-cyan to-magenta flex items-center justify-center shrink-0">
                                    <Sparkles className="w-6 h-6 text-white" />
                                </div>
                                <div className="flex-1">
                                    <h3 className="font-semibold font-display text-white mb-2">AI-Generated Document</h3>
                                    <p className="text-sm text-white/60 leading-relaxed mb-4">
                                        This contract was drafted by Sudo using professional legal language based on your negotiation discussion.
                                        While designed to be comprehensive, please have a qualified legal professional review this document
                                        before using it for binding agreements.
                                    </p>
                                    <div className="flex flex-wrap gap-4 text-xs text-white/40">
                                        <div className="flex items-center gap-1.5">
                                            <Shield className="w-3.5 h-3.5" />
                                            Privacy Protected
                                        </div>
                                        <div className="flex items-center gap-1.5">
                                            <Clock className="w-3.5 h-3.5" />
                                            Generated Instantly
                                        </div>
                                        <div className="flex items-center gap-1.5">
                                            <FileText className="w-3.5 h-3.5" />
                                            Based on Negotiation
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </CardContent>
                    </Card>

                    {/* Actions Footer */}
                    <div className="flex flex-col sm:flex-row gap-4 pt-4">
                        <Button variant="secondary" onClick={() => router.push('/contracts')} className="sm:flex-1">
                            <ArrowLeft className="w-4 h-4" />
                            Back to Contracts
                        </Button>
                        <Button onClick={handleDownload} loading={downloading} className="sm:flex-1">
                            <Download className="w-4 h-4" />
                            Download Contract
                        </Button>
                    </div>
                </motion.div>
            </main>
        </div>
    );
}
